apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: api
  name: tripinsights-ingress-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /api/user
        backend:
          service:
            name: tripinsights-userprofile-service
            port:
              number: 80
  - http:
      paths:
      - pathType: Prefix
        path: /api/user-java
        backend:
          service:
            name: tripinsights-userjava-service
            port:
              number: 80
  - http:
      paths:
      - pathType: Prefix
        path: /api/trips
        backend:
          service:
            name: tripinsights-trips-service
            port:
              number: 80
  - http:
      paths:
      - pathType: Prefix
        path: /api/poi
        backend:
          service:
            name: tripinsights-poi-service
            port:
              number: 80