apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Make sure the correct namespace is chosen. This must correspond to where the service endpoints are
  namespace: web
  name: tripinsights-ingress-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # No need to put any rewrite rules in for this scenario
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: tripinsights-tripviewer-service
            port:
              number: 80