apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-tripviewer-deployment
  labels:
    app: tripinsights-tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripinsights-tripviewer
  template:
    metadata:
      labels:
        app: tripinsights-tripviewer
    spec:
      containers:
        - name: tripinsights-tripviewer
          image: registryztd0636.azurecr.io/tripinsights/tripviewer:1.0
          ports:
          - containerPort: 80
          env:
          - name: TRIPS_API_ENDPOINT
            value: http://tripinsights-trips-service
          - name: USERPROFILE_API_ENDPOINT
            value: http://tripinsights-userprofile-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tripinsights-tripviewer
  name: tripinsights-tripviewer-loadbalancer
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: tripinsights-tripviewer
  type: LoadBalancer