kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-user-full-access
subjects:
- kind: Group
  namespace: web
  name: 3f0985ab-aa81-4acb-aa5f-73aa37bf4a2a